name = "CoordinatesSystems"
uuid = "46fde914-2a1c-4f77-9b2f-1c21d94fe0f1"
authors = ["Jerome Guterl"]
version = "1.0.0-DEV"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
MacroTools = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
